name: Setup Kind Cluster with Ingress
description: Create a test Kubernetes cluster with Kind and install an ingress controller
inputs:
  clusterName:
    description: Name of the Kind cluster to create
    required: false
    default: 'kind'
  installIngress:
    description: Whether to install the ingress controller
    required: false
    default: 'false'
  installPrometheus:
    description: Whether to install Prometheus
    required: false
    default: 'false'

runs:
  using: composite
  steps:
    - name: Create Kind Cluster
      id: create-cluster
      shell: bash
      run: |
        kind create cluster --name ${{inputs.clusterName}} --config ${GITHUB_ACTION_PATH}/kind-config.yaml

    - name: Install Ingress Controller
      id: install-ingress
      if: ${{ inputs.installIngress == 'true' }}
      shell: bash
      run: |
        kubectl apply -f ${GITHUB_ACTION_PATH}/ingress-nginx.yaml
    
    - name: Wait for Ingress Controller to be Ready
      id: wait-ingress
      if: ${{ inputs.installIngress == 'true' }}
      shell: bash
      run: |
        kubectl wait --namespace ingress-nginx \
          --for=condition=ready pod \
          --selector=app.kubernetes.io/component=controller \
          --timeout=120s

    - name: Install Prometheus
      id: install-prometheus
      if: ${{ inputs.installPrometheus == 'true' }}
      shell: bash
      run: |
        kubectl apply -f ${GITHUB_ACTION_PATH}/prometheus.yaml
        kubectl apply -f ${GITHUB_ACTION_PATH}/prometheus-ingress.yaml
        kubectl apply -f ${GITHUB_ACTION_PATH}/prometheus-service