defaultArgs:
  - --cert-dir=/tmp
  - --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname
  - --kubelet-use-node-status-port
  # Use the minimum resolution (10s) as CI duration is short
  - --metric-resolution=10s
  - --kubelet-request-timeout=8s

args: ["--kubelet-insecure-tls"]